name: "Terraform-Plan-Infra-Plan"

on:
  push:
    branches:
      - master

jobs:
  terraform:
    name: "Terraform"
    runs-on: self-hosted
    env:	
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRETE_ID }}
      AWS_REGION: 'us-east-1'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Fmt
        id: fmt
        run: terraform fmt -check -diff
        continue-on-error: true

      -   name: Terraform Init
          id: init
          run: terraform init
          continue-on-error: true

      -   name: Terraform Validate
          id: validate
          run: terraform validate 
          continue-on-error: true

      -  name: Terraform Plan
         id: plan
         run: terraform plan 
		
		
		
